### ISSUE TITLE
Set participants dialog issue

### ISSUE THREAD

**Issue by hasancbngl** [Xkoranate-Mobile-Development-Team/Xkoranate-Mobile#14]
I go to settings => new game => clicked to floating action button to add participants and
the set participants became very small when I click any  (set participants, team name etc or skill level) of the fields  so 3 of the fields the dialog became smaller and the fields are  not editable. 

also it might look nicer if the keybard is hidden while you're not typing. 
=> it logs in without filling the fields after I registrated and then "I got the please input all values toast".

**Comment by tumininucodes** [comment]
Would fix the keyboard issue. The login is bypassed for now for debugging purpose
